package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCustomerComment extends BaseModule<TCustomerComment> implements Serializable {
    public int customerCommentId;
    public String serviceComment;
    public String serviceQuality;
    public String caption;
    public String comment;
    public java.util.ArrayList<TParcelInfo> packages;
}
