package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TInvoiceInfo extends BaseModule<TInvoiceInfo> implements Serializable {
    public String payDate;
    public int paymentBillId;
    public String paymentNumber;
    public String payStatus;
    public String chargeWeight;
    public String createDate;
    public java.util.ArrayList<TPaymentBillCategory> packageBillDetail;
    public int packageId;
    public String packageNumber;
    public String packageWeight;
    public String productTotalPrice;
    public String total;
}
