package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrderDetailRemark extends BaseModule<TOrderDetailRemark> implements Serializable {
    public int orderRemarkId;
    public String remark;
    public boolean needReply;
    public String attachment;
    public String createDate;
    public String creator;
    public int offsetId;
    public String remarkFlag;
}
