package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrder extends BaseModule<TOrder> implements Serializable {
    public int orderId;
    public String orderNumber;
    public String productImage;
    public String productName;
    public boolean gstFee;
    public boolean insured;
    public String sellerDiscount;
    public double weight;
    public double volumeWeight;
    public String wayBill;
    public String alternative;
    public String shipperName;
    public String vendorName;
    public String originCode;
    public String warehouseCode;
    public int shipmentTypeId;
    public int purchaseSourceId;
    public String payDate;
}
