package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPackageDetail extends BaseModule<TPackageDetail> implements Serializable {
    public TPackage tPackage;
    public TPaymentBill paymentBill;
    public java.util.ArrayList<TOrder> orders;
    public java.util.ArrayList<TOrderDetailRemark> orderRemarks;
}
