package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcelProduct extends BaseModule<TParcelProduct> implements Serializable {
    public String name;
    public String desc;
    public String url;
    public String pic;
    public int quantity;
}
