package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcelDetailInfo extends BaseModule<TParcelDetailInfo> implements Serializable {
    public int arrivedCount;
    public int notArrivedCount;
    public java.util.ArrayList<TParcelInfo> tPackage;
}
