package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcel extends BaseModule<TParcel> implements Serializable {
    public String parcelNumber;
    public java.util.ArrayList<TParcelSection> sections;
    public java.util.ArrayList<TParcelProduct> products;
}
