package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcelDeliveryInfo extends BaseModule<TParcelDeliveryInfo> implements Serializable {
    public String deliveryMethodName;
    public String title;
    public String deliveryPic;
    public String address;
    public String recipient;
    public String phone;
    public java.util.ArrayList<String> dates;
    public String desc;
}
