package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcelSummary extends BaseModule<TParcelSummary> implements Serializable {
    public String parcelNumber;
    public java.util.ArrayList<String> pics;
    public java.util.ArrayList<TParcelDetailItem> items;
    public boolean hasPendingPayment;
    public boolean canArrangeDelivery;
    public boolean canArrangeEzbuyDelivery;
}
