package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcelSummaryItem extends BaseModule<TParcelSummaryItem> implements Serializable {
    public int packageCount;
    public int sortBy;
    public String statusCode;
    public String statusName;
}
