package com.daigou.sg.rpc.parcel;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipment extends BaseModule<TShipment> implements Serializable {
    public int shipmentId;
    public String localDeliveryMethod;
    public String stationName;
    public String periodName;
    public String localDeliveryDate;
    public String shipToAddress;
    public String shipToName;
    public String shipToPhone;
    public String shipToZip;
    public String shipToCity;
    public String shipToState;
    public String regionName;
    public String regionId;
    public String mrtStationItemId;
    public String neighbourhoodStationItemId;
    public int selfStationId;
    public double total;
    public String dayOfWeek;
    public boolean isEzShipping;
    public boolean canBeEdited;
    public String paymentNumber;
    public java.util.ArrayList<TParcelInfo> tPackage;
}
