package com.daigou.sg.webapi.common;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrderSimple extends BaseModule<TOrderSimple> implements Serializable {
    public int orderID;
    public String orderNumber;
    public String itemName;
    public int quantity;
    public String price;
    public String itemPic;
    public String sku;
    public String status;
    public String productUrl;
    public boolean hasReview;
}
