package com.daigou.sg.webapi.common;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TProductCommon extends BaseModule<TProductCommon> implements Serializable {
    public String url;
    public String name;
    public String pictureUrl;
    public String localUnitPrice;
    public String originalLocalUnitPrice;
    public String discountRate;
    public boolean isCashOff;
}
