package com.daigou.sg.webapi.common;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TRelatedType implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("3")
	OTHER(3),
	@SerializedName("1")
	PRODUCT(1),
	@SerializedName("2")
	PARCEL(2);


	int type;

    TRelatedType(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
