package com.daigou.sg.webapi.popup;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.Response.Listener;
import com.android.volley.VolleyError;
import com.daigou.sg.rpc.BaseModule;
import com.daigou.sg.rpc.GsonUtils;
import com.daigou.sg.rpc.RpcRequest;
import com.daigou.sg.rpc.RpcResponse;
import com.daigou.sg.rpc.TRpc;
import com.google.gson.Gson;

import java.nio.charset.Charset;

public class PopupService {
    private static final Gson gson = GsonUtils.getGsonInstance();
    private static int msgID = 1;

    private PopupService() {
        // Constructor hidden because this is a singleton
    }

    private static String getMsgID() {
        msgID += 1;
        return Integer.toString(msgID);
    }

    public static RpcRequest GetPopupBanner(final String countryCode, final Listener<TPopup> listener) {
        RpcResponse res = new RpcResponse(TPopup.class, listener,false,false);
        java.util.HashMap<String, Object> args = new java.util.HashMap<String, Object>();
        
        args.put("countryCode", countryCode);

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "Popup/GetPopupBanner", res, args);
        TRpc.getQueue().add(req);
        return req;
    }
}
