package com.daigou.sg.webapi.popup;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPopup extends BaseModule<TPopup> implements Serializable {
    public String name;
    public String picture;
    public String url;
}
