package com.daigou.sg.webapi.reply.pending;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.Response.Listener;
import com.android.volley.VolleyError;
import com.daigou.sg.rpc.BaseModule;
import com.daigou.sg.rpc.GsonUtils;
import com.daigou.sg.rpc.RpcRequest;
import com.daigou.sg.rpc.RpcResponse;
import com.daigou.sg.rpc.TRpc;
import com.google.gson.Gson;

import java.nio.charset.Charset;

public class PendingReplyService {
    private static final Gson gson = GsonUtils.getGsonInstance();
    private static int msgID = 1;

    private PendingReplyService() {
        // Constructor hidden because this is a singleton
    }

    private static String getMsgID() {
        msgID += 1;
        return Integer.toString(msgID);
    }

    public static RpcRequest UserGetPendingReplies(final TPendingRepleyDomain domain, final int offset, final int limit, final Listener<java.util.ArrayList<TPendingReplyItem>> listener) {
        RpcResponse res = new RpcResponse(TPendingReplyItem.class, listener, true,false);
        java.util.HashMap<String, Object> args = new java.util.HashMap<String, Object>();
        
        int domainValue = ((com.daigou.sg.rpc.DeserializerEnum) domain).getValue();
        args.put("domain", domainValue);
        
        args.put("offset", offset);
        
        args.put("limit", limit);

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "PendingReply/UserGetPendingReplies", res, args);
        TRpc.getQueue().add(req);
        return req;
    }

    public static RpcRequest UserGetPendingReplyCount(final TPendingRepleyDomain domain, final Listener<Integer> listener) {
        RpcResponse res = new RpcResponse(Integer.class, listener,false,false);
        java.util.HashMap<String, Object> args = new java.util.HashMap<String, Object>();
        
        int domainValue = ((com.daigou.sg.rpc.DeserializerEnum) domain).getValue();
        args.put("domain", domainValue);

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "PendingReply/UserGetPendingReplyCount", res, args);
        TRpc.getQueue().add(req);
        return req;
    }
}
