package com.daigou.sg.webapi.reply.pending;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrderRemarkItem extends BaseModule<TOrderRemarkItem> implements Serializable {
    public int id;
    public String remark;
    public boolean needReply;
    public String attachments;
    public String createDate;
    public String creator;
    public int offsetId;
    public boolean isForRepack;
}
