package com.daigou.sg.webapi.reply.pending;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TPendingRepleyDomain implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("0")
	ALL(0),
	@SerializedName("1")
	PROCESSINGORDER(1),
	@SerializedName("2")
	SHIPMENT(2);


	int type;

    TPendingRepleyDomain(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
