package com.daigou.sg.webapi.reply.pending;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPendingReplyItem extends BaseModule<TPendingReplyItem> implements Serializable {
    public String message;
    public com.daigou.sg.webapi.common.TRelatedType relatedType;
    public com.daigou.sg.webapi.common.TOrderSimple order;
    public com.daigou.sg.rpc.ezshipment.TPackage parcel;
    public TOrderRemarkItem orderRemark;
    public com.daigou.sg.rpc.ezshipment.TParcelRemark parcelRemark;
    public com.daigou.sg.webapi.common.TServiceType orderServiceType;
    public java.util.ArrayList<TOrderRemarkItem> orderRemarkWeb;
    public java.util.ArrayList<com.daigou.sg.rpc.ezshipment.TParcelRemark> parcelRemarkWeb;
}
