package com.daigou.sg.rpc.order;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOrder extends BaseModule<TOrder> implements Serializable {
    public int id;
    public String orderNumber;
    public String productImage;
    public String productName;
    public boolean gstFee;
    public boolean insured;
    public String sellerDiscount;
    public int packageId;
    public String altProductName;
    public String sku;
    public String altSku;
    public String shipmentTypeName;
    public String altShipmentTypeName;
    public String shipmentTypeId;
    public double unitPrice;
    public double localUnitPrice;
    public int qty;
    public String warehouseCode;
    public String orderStatus;
}
