package com.daigou.sg.rpc.order;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShip4MeOrderDetailInfo extends BaseModule<TShip4MeOrderDetailInfo> implements Serializable {
    public java.util.ArrayList<com.daigou.sg.rpc.primeorder.TTitleValueItem> courierInfo;
    public java.util.ArrayList<String> takenPhotos;
    public String repackService;
    public int storageDays;
    public double weight;
}
