package com.daigou.sg.rpc.offset;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOffset extends BaseModule<TOffset> implements Serializable {
    public int id;
    public String offsetType;
    public String total;
    public String note;
    public String payDate;
}
