package com.daigou.sg.webapi.order.processing;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TProcessingOrderGroup extends BaseModule<TProcessingOrderGroup> implements Serializable {
    public int itemCount;
    public String totalAmount;
    public com.daigou.sg.webapi.common.TServiceType serviceType;
    public String status;
    public java.util.ArrayList<com.daigou.sg.webapi.common.TOrderSimple> sampleOrders;
    public boolean hasMoreOrders;
    public int paymentID;
    public String paymentNumber;
    public String additionalDescription;
    public String maxCreatedDate;
}
