package com.daigou.sg.rpc.message;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TMessageType implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("2")
	ORDERARRIVED(2),
	@SerializedName("3")
	PARCELARRANGEABLE(3),
	@SerializedName("4")
	ENQUIRY(4),
	@SerializedName("5")
	WEB(5),
	@SerializedName("6")
	PARCELPENDING(6),
	@SerializedName("0")
	NORMAL(0),
	@SerializedName("1")
	ORDERPENDING(1);


	int type;

    TMessageType(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
