package com.daigou.sg.rpc.message;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TMessage extends BaseModule<TMessage> implements Serializable {
    public int id;
    public String messageType;
    public String message;
    public boolean isRead;
    public int orderId;
    public int packageId;
    public String url;
    public String updateDate;
    public TMessageType type;
    public com.daigou.sg.webapi.readytoship.TReadyToShipGroup readyToShipGroup;
}
