package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TBannerGroupLayoutInfo extends BaseModule<TBannerGroupLayoutInfo> implements Serializable {
    public String layoutType;
    public double unitBannerRatio;
}
