package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TBanner extends BaseModule<TBanner> implements Serializable {
    public String name;
    public String imageURL;
    public String link;
    public String fallbackLink;
}
