package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TBannerGroup extends BaseModule<TBannerGroup> implements Serializable {
    public String name;
    public java.util.ArrayList<TBanner> banners;
    public TBannerGroupLayoutInfo layoutInfo;
}
