package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCreditVoucher extends BaseModule<TCreditVoucher> implements Serializable {
    public int credit;
    public int offset;
    public String imageURL;
    public String title;
    public String voucherDescription;
    public boolean isAvailable;
}
