package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCustomerCredit extends BaseModule<TCustomerCredit> implements Serializable {
    public int customerCreditId;
    public int oldCredit;
    public int credit;
    public int newCredit;
    public String creditDate;
    public String remark;
}
