package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCustomer extends BaseModule<TCustomer> implements Serializable {
    public int id;
    public String nickName;
    public String email;
    public String telephone;
}
