package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCustomerRemindInfo extends BaseModule<TCustomerRemindInfo> implements Serializable {
    public int Credits;
    public int EnquiryCount;
    public int ReviewCount;
    public int AddressCount;
}
