package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCustomerDefaultInfo extends BaseModule<TCustomerDefaultInfo> implements Serializable {
    public int id;
    public String customerLevel;
    public int vouchers;
    public int credits;
    public int enquiryCount;
    public int reviewCount;
    public String headPortraits;
    public String defaultLanguage;
    public boolean ezShipping;
    public boolean newsLetter;
    public boolean notification;
    public String notificationEmail;
    public String sex;
    public String birthDate;
    public java.util.ArrayList<TOriginSetting> originSettings;
    public TPrimeSetting primeInfo;
}
