package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TFavoritesItem extends BaseModule<TFavoritesItem> implements Serializable {
    public String Url;
    public String ProductName;
    public String ProductImage;
    public double Price;
    public String VendorName;
}
