package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOriginSetting extends BaseModule<TOriginSetting> implements Serializable {
    public String originCode;
    public int shipmentTypeId;
    public String warehouseCode;
    public String altWarehouseName;
    public String altShipmentTypeName;
}
