package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimeSetting extends BaseModule<TPrimeSetting> implements Serializable {
    public boolean primer;
    public boolean displayPrimeZone;
    public boolean isPrimeCheckoutAvailable;
    public String primeStartDate;
    public String primeEndDate;
}
