package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TRenewSessionResult extends BaseModule<TRenewSessionResult> implements Serializable {
    public boolean isAuthroized;
    public String message;
    public String altMessage;
}
