package com.daigou.sg.rpc.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TVoucher extends BaseModule<TVoucher> implements Serializable {
    public int id;
    public String voucherNumber;
    public String altVoucherName;
    public int faceValue;
    public String voucherImage;
    public String endDate;
}
