package com.daigou.sg.webapi.readytoship;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TReadyToShipGroup extends BaseModule<TReadyToShipGroup> implements Serializable {
    public int itemsCount;
    public com.daigou.sg.webapi.common.TServiceType serviceType;
    public String warehouseCode;
    public String shippingMethodCode;
    public String shippingMethodName;
    public java.util.ArrayList<String> itemsPics;
    public String status;
    public int freeStorageDays;
    public int chargedStorageDays;
    public double storageFee;
    public int notArrivedItemCount;
}
