package com.daigou.sg.webapi.readytoship;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TReadyToShipOrderItem extends BaseModule<TReadyToShipOrderItem> implements Serializable {
    public double weight;
    public int storageDays;
    public String memoToSelf;
    public double declareValue;
    public boolean isDeclareValueEditable;
    public java.util.ArrayList<String> availableShippingMethodCodes;
    public com.daigou.sg.webapi.common.TOrderSimple relatedOrder;
    public java.util.ArrayList<com.daigou.sg.webapi.common.TOrderSimple> relatedOrderWeb;
}
