package com.daigou.sg.webapi.readytoship;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShip4MeCheckoutInfo extends BaseModule<TShip4MeCheckoutInfo> implements Serializable {
    public java.util.ArrayList<Integer> orderIDs;
    public double declareValues;
    public String warehouseCode;
    public com.daigou.sg.rpc.checkout.TCartCheckoutInfo info;
}
