package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class SearchResult extends BaseModule<SearchResult> implements Serializable {
    public java.util.ArrayList<TSimpleProduct> products;
    public java.util.ArrayList<String> sorts;
    public java.util.ArrayList<SearchFilter> filters;
}
