package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class SearchFilterCond extends BaseModule<SearchFilterCond> implements Serializable {
    public String filterName;
    public String fieldName;
}
