package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class SearchFilter extends BaseModule<SearchFilter> implements Serializable {
    public String name;
    public java.util.ArrayList<SearchFilterField> fields;
    public boolean emphasized;
}
