package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCharacteristic extends BaseModule<TCharacteristic> implements Serializable {
    public String propkey;
    public String actualValue;
    public String remark;
    public String imageUrl;
    public boolean isSelected;
}
