package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TGroupBuyInfo extends BaseModule<TGroupBuyInfo> implements Serializable {
    public boolean groupbuyAvailable;
    public long beginTimeSpan;
    public long endTimeSpan;
    public int totalStock;
    public int soldStock;
    public int usableStock;
    public java.util.ArrayList<TGroupBuyItemsInfo> info;
    public String deposit;
}
