package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TProductExtension extends BaseModule<TProductExtension> implements Serializable {
    public long cid;
    public String vendorName;
    public String productName;
    public double unitPrice;
    public double shippingFee;
    public String productUrl;
    public String productImage;
    public String originCode;
    public String shopName;
    public String location;
    public String aroundwWarehouse;
    public boolean isShippingFee;
    public int favoritesItemId;
    public int favoriteCatId;
    public String specialHandlingFeeMessage;
    public double specialHandlingFeePercent;
    public java.util.ArrayList<String> propertyNames;
    public java.util.ArrayList<TShippingFee> shippingFees;
    public java.util.ArrayList<String> descriptionImages;
    public java.util.ArrayList<TCharacteristicGroup> characteristicGroups;
    public java.util.ArrayList<TSku> skus;
    public java.util.ArrayList<String> itemImgs;
    public boolean isEZBuy;
    public String priceSymbol;
    public String localUnitPrice;
    public double localShipmentFee;
    public String errMsg;
    public String eta;
    public boolean displayShippingIcon;
    public String altProductName;
    public java.util.ArrayList<TCharacteristicGroup> altCharacteristicGroups;
    public boolean primeAvailable;
    public boolean isShippedBySea;
    public boolean isContainGSTFee;
    public TFlashSalesInfo flashSalesInfo;
    public double originalUnitPrice;
    public String originalLocalUnitPrice;
    public String discountRate;
    public boolean isCashOffProduct;
    public TGroupBuyInfo groupbuyInfo;
    public String shareUrl;
}
