package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TProductReviewDetail extends BaseModule<TProductReviewDetail> implements Serializable {
    public int id;
    public String productUrl;
    public int userId;
    public int rating;
    public int helpfulCount;
    public String comment;
    public String pictures;
    public boolean setHelpful;
    public String nickName;
    public String headPortraits;
    public String sku;
    public String createDate;
}
