package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSimpleProduct extends BaseModule<TSimpleProduct> implements Serializable {
    public String productName;
    public String productUrl;
    public String productImage;
    public String originCode;
    public boolean isEZBuy;
    public String localUnitPrice;
    public String originalLocalUnitPrice;
    public String discountRate;
    public boolean isCashOffProduct;
}
