package com.daigou.sg.rpc.product;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSku extends BaseModule<TSku> implements Serializable {
    public String price;
    public String properties;
    public String propertiesName;
    public long quantity;
    public long skuId;
    public long skuSpecId;
    public String status;
    public long withHoldQuantity;
}
