package com.daigou.sg.rpc.favorite;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TFavoriteResult extends BaseModule<TFavoriteResult> implements Serializable {
    public String message;
    public boolean result;
}
