package com.daigou.sg.rpc.favorite;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TFavoriteCategory extends BaseModule<TFavoriteCategory> implements Serializable {
    public int id;
    public String name;
    public int productCount;
    public String productImage;
}
