package com.daigou.sg.webapi.account;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TLoginInfo extends BaseModule<TLoginInfo> implements Serializable {
    public TResult result;
    public TUserInfo userInfo;
    public String customerCookie;
}
