package com.daigou.sg.webapi.account;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOauthLoginV2Params extends BaseModule<TOauthLoginV2Params> implements Serializable {
    public String area;
    public String userType;
    public String email;
    public String accessToken;
    public String userId;
    public String platform;
    public String deviceToken;
    public String UDID;
    public String deviceInfo;
}
