package com.daigou.sg.webapi.account;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TResult extends BaseModule<TResult> implements Serializable {
    public int errorCode;
    public String errorMessage;
}
