package com.daigou.sg.webapi.account;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TUserInfo extends BaseModule<TUserInfo> implements Serializable {
    public int customerId;
    public String customerName;
    public String sessionId;
    public double longitude;
    public double latitude;
    public String deviceToken;
    public String nickName;
    public String selfHelpHandPhone;
    public String telephone;
}
