package com.daigou.sg.rpc.enquiry;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TEnquiryCategory extends BaseModule<TEnquiryCategory> implements Serializable {
    public int enquiryCategoryId;
    public String enquiryCode;
    public String altEnquiry;
    public String replyDay;
}
