package com.daigou.sg.rpc.enquiry;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TEnquiry extends BaseModule<TEnquiry> implements Serializable {
    public int id;
    public String caption;
    public String content;
    public String updateDate;
    public String originCode;
    public int serviceTypeId;
    public int enquiryCategoryId;
    public String referenceNo;
    public String ticketNo;
    public String attachments;
    public String newestQuestion;
    public String newestAnswer;
    public boolean canDelete;
}
