package com.daigou.sg.rpc.enquiry;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TEnquiryServiceType extends BaseModule<TEnquiryServiceType> implements Serializable {
    public int id;
    public String purchaseType;
    public String serviceName;
    public String altServiceName;
}
