package com.daigou.sg.rpc.enquiry;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TEnquiryDetail extends BaseModule<TEnquiryDetail> implements Serializable {
    public int CustomerServiceItemId;
    public int CustomerServiceId;
    public int CustomerId;
    public int UserId;
    public String Caption;
    public String Content;
    public String IsActive;
    public String CreateBy;
    public String CreateDate;
    public String UpdateBy;
    public String UpdateDate;
    public String Type;
    public String CatalogCode;
    public String AskAttachment;
    public String IsViewed;
    public String IsReplied;
    public boolean IsCompleted;
    public boolean CanDelete;
    public int RowNumber;
    public int ParentId;
    public String OriginCode;
    public int ServiceTypeId;
    public int EnquiryCategoryId;
    public String ReferenceNo;
    public String TicketNo;
    public int ConsultCount;
    public String NewestQuestion;
    public String NewestAnswer;
}
