package com.daigou.sg.rpc.enquiry;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TServiceType extends BaseModule<TServiceType> implements Serializable {
    public int ServiceTypeId;
    public String PurchaseType;
    public String ServiceName;
    public String AltServiceName;
}
