package com.daigou.sg.rpc.utility;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TBasicInfo extends BaseModule<TBasicInfo> implements Serializable {
    public String faqUrl;
    public String customerServiceEmail;
    public String hotline;
    public String address;
    public String quickGuideUrl;
    public String addressDescription;
    public String smallMapUrl;
    public String bigMapUrl;
    public double leastVersion;
}
