package com.daigou.sg.rpc.utility;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TExchangeRate extends BaseModule<TExchangeRate> implements Serializable {
    public String originCode;
    public double rate;
    public String priceSymbol;
}
