package com.daigou.sg.rpc.utility;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TGuidePage extends BaseModule<TGuidePage> implements Serializable {
    public java.util.ArrayList<String> pics;
    public int version;
    public String expireDate;
    public int displayTimes;
    public String startDate;
}
