package com.daigou.sg.rpc.utility;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPromotionAd extends BaseModule<TPromotionAd> implements Serializable {
    public String promotionName;
    public String imagePath;
    public String hyperLink;
}
