package com.daigou.sg.rpc.utility;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipmentType extends BaseModule<TShipmentType> implements Serializable {
    public int id;
    public String originCode;
    public String shipmentTypeCode;
    public String shipmentTypeName;
    public String altShipmentTypeName;
    public double minimumWeightFee;
    public double continueWeightFee;
    public String estimatedEtaDays;
    public String desc;
}
