package com.daigou.sg.rpc.utility;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TTopUpBank extends BaseModule<TTopUpBank> implements Serializable {
    public String bankName;
    public String accountInfo;
}
