package com.daigou.sg.rpc.prepay;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TDealHistory extends BaseModule<TDealHistory> implements Serializable {
    public String id;
    public long date;
    public double number;
    public TStatus status;
}
