package com.daigou.sg.rpc.prepay;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TStatus implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("0")
	CANCEL(0),
	@SerializedName("1")
	PENDING(1),
	@SerializedName("2")
	COMFIRMED(2),
	@SerializedName("3")
	REJECT(3);


	int type;

    TStatus(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
