package com.daigou.sg.rpc.prepay;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.Response.Listener;
import com.android.volley.VolleyError;
import com.daigou.sg.rpc.BaseModule;
import com.daigou.sg.rpc.GsonUtils;
import com.daigou.sg.rpc.RpcRequest;
import com.daigou.sg.rpc.RpcResponse;
import com.daigou.sg.rpc.TRpc;
import com.google.gson.Gson;

import java.nio.charset.Charset;

public class UserPrepayService {
    private static final Gson gson = GsonUtils.getGsonInstance();
    private static int msgID = 1;

    private UserPrepayService() {
        // Constructor hidden because this is a singleton
    }

    private static String getMsgID() {
        msgID += 1;
        return Integer.toString(msgID);
    }

    public static RpcRequest UserGetTopUpHistory(final int limit, final int offset, final Listener<java.util.ArrayList<TDealHistory>> listener) {
        RpcResponse res = new RpcResponse(TDealHistory.class, listener, true,false);
        java.util.HashMap<String, Object> args = new java.util.HashMap<String, Object>();
        
        args.put("limit", limit);
        
        args.put("offset", offset);

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "UserPrepay/UserGetTopUpHistory", res, args);
        TRpc.getQueue().add(req);
        return req;
    }

    public static RpcRequest UserGetTransationHistory(final int limit, final int offset, final Listener<java.util.ArrayList<TDealHistory>> listener) {
        RpcResponse res = new RpcResponse(TDealHistory.class, listener, true,false);
        java.util.HashMap<String, Object> args = new java.util.HashMap<String, Object>();
        
        args.put("limit", limit);
        
        args.put("offset", offset);

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "UserPrepay/UserGetTransationHistory", res, args);
        TRpc.getQueue().add(req);
        return req;
    }

    public static RpcRequest UserGetWithdrawHistory(final int limit, final int offset, final Listener<java.util.ArrayList<TDealHistory>> listener) {
        RpcResponse res = new RpcResponse(TDealHistory.class, listener, true,false);
        java.util.HashMap<String, Object> args = new java.util.HashMap<String, Object>();
        
        args.put("limit", limit);
        
        args.put("offset", offset);

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "UserPrepay/UserGetWithdrawHistory", res, args);
        TRpc.getQueue().add(req);
        return req;
    }
}
