package com.daigou.sg.webapi.payment.pending;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPaymentDetail extends BaseModule<TPaymentDetail> implements Serializable {
    public TPaymentSimple info;
    public java.util.ArrayList<com.daigou.sg.webapi.common.TOrderSimple> relatedOrders;
    public java.util.ArrayList<com.daigou.sg.rpc.primeorder.TTitleValueItem> orderSummaryInfo;
    public java.util.ArrayList<com.daigou.sg.rpc.ezshipment.TPackageDetail> relatedParcels;
    public double prePay;
}
