package com.daigou.sg.webapi.payment.pending;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPendingPaymentResult extends BaseModule<TPendingPaymentResult> implements Serializable {
    public java.util.ArrayList<TPaymentSimple> payments;
    public double prePay;
    public int totalCount;
}
