package com.daigou.sg.webapi.usercoin;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TCoinRecordDomain implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("0")
	ALL(0),
	@SerializedName("1")
	USED(1),
	@SerializedName("2")
	GAINED(2),
	@SerializedName("3")
	EXPIRED(3);


	int type;

    TCoinRecordDomain(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
