package com.daigou.sg.webapi.usercoin;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCoinRecord extends BaseModule<TCoinRecord> implements Serializable {
    public long id;
    public long timestamp;
    public int amount;
    public String note;
    public String noteSpec;
}
