package com.daigou.sg.webapi.groupbuy;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TGroupbuyProduct extends BaseModule<TGroupbuyProduct> implements Serializable {
    public String productUrl;
    public String productName;
    public String productImage;
    public String localPrice;
    public int currentStock;
    public String startTime;
    public String endTime;
    public int originStock;
    public double stockPercent;
    public int currentJoinCount;
    public String groupbuyNo;
    public int groupbuyStatus;
    public String productId;
}
