package com.daigou.sg.webapi.groupbuy;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSearchCondition extends BaseModule<TSearchCondition> implements Serializable {
    public int searchType;
    public String tag;
    public int limit;
    public String productId;
}
