package com.daigou.sg.webapi.mine;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.Response.Listener;
import com.android.volley.VolleyError;
import com.daigou.sg.rpc.BaseModule;
import com.daigou.sg.rpc.GsonUtils;
import com.daigou.sg.rpc.RpcRequest;
import com.daigou.sg.rpc.RpcResponse;
import com.daigou.sg.rpc.TRpc;
import com.google.gson.Gson;

import java.nio.charset.Charset;

public class MineService {
    private static final Gson gson = GsonUtils.getGsonInstance();
    private static int msgID = 1;

    private MineService() {
        // Constructor hidden because this is a singleton
    }

    private static String getMsgID() {
        msgID += 1;
        return Integer.toString(msgID);
    }

    public static RpcRequest UserGetOrderStatusInfo(final Listener<TMineOrderStatus> listener) {
        RpcResponse res = new RpcResponse(TMineOrderStatus.class, listener,false,false);
        java.util.HashMap<String, Object> args = null;

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "Mine/UserGetOrderStatusInfo", res, args);
        TRpc.getQueue().add(req);
        return req;
    }

    public static RpcRequest UserGetYouMayLike(final Listener<java.util.ArrayList<com.daigou.sg.rpc.product.TSimpleProduct>> listener) {
        RpcResponse res = new RpcResponse(com.daigou.sg.rpc.product.TSimpleProduct.class, listener, true,false);
        java.util.HashMap<String, Object> args = null;

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "Mine/UserGetYouMayLike", res, args);
        TRpc.getQueue().add(req);
        return req;
    }
}
