package com.daigou.sg.webapi.mine;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TMineOrderStatus extends BaseModule<TMineOrderStatus> implements Serializable {
    public double prePay;
    public int numberOfPendingPayment;
    public int numberOfProcessing;
    public int numberOfreadyToShip;
    public int numberOfshipment;
    public boolean isPendingPaymentActionNeeded;
    public boolean isProcessingActionNeeded;
    public boolean isReadyToShipActionNeeded;
    public boolean isShipmentActionNeeded;
    public int numberOfShoppingCart;
}
