package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCartCheckoutInfo extends BaseModule<TCartCheckoutInfo> implements Serializable {
    public String checkoutType;
    public String originCode;
    public String shippingMethod;
    public String deliveryMethod;
    public int deliveryMethodId;
    public String receipient;
    public String phone;
    public String coupon;
    public int credit;
    public String deliveryDate;
    public String deliveryTimeSlot;
    public boolean insured;
    public String warehouse;
    public boolean isAuthorizeBalance;
    public java.util.ArrayList<TDeliveryMethodExtension> deliveryMethodExtensions;
}
