package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCartBill extends BaseModule<TCartBill> implements Serializable {
    public boolean isEzBuy;
    public int productCount;
    public int sensitiveProductCount;
    public double totalFee;
    public double prepay;
    public java.util.ArrayList<TBillDetail> billDetails;
    public boolean isCouponValid;
    public double weight;
    public java.util.ArrayList<String> validVoucherCodes;
}
