package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCheckoutVoucher extends BaseModule<TCheckoutVoucher> implements Serializable {
    public String code;
    public boolean available;
    public boolean expired;
    public String name;
    public String desc;
    public String pic;
}
