package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCheckoutForm extends BaseModule<TCheckoutForm> implements Serializable {
    public boolean isEzBuy;
    public int sensitiveItemCount;
    public String shippingMethodCode;
    public String shippingMethodName;
    public String shippingMethodDesc;
    public String deliveryMethod;
    public int deliveryMethodId;
    public String deliveryMethodName;
    public String deliveryMethodDesc;
    public boolean insured;
    public int credit;
    public String receipient;
    public String phone;
    public int itemCount;
    public double weight;
    public boolean containsFlashSalesProduct;
    public String msg;
}
