package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCollectStation extends BaseModule<TCollectStation> implements Serializable {
    public int id;
    public String stationName;
    public String stationAddress;
    public String telephone;
    public double maxWeight;
    public int aheadOfDay;
    public double longitude;
    public double latitude;
    public String imageUrl;
    public String desc;
    public String shortDesc;
}
