package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TDeliveryAddress extends BaseModule<TDeliveryAddress> implements Serializable {
    public int addressID;
    public String deliveryMethodCode;
    public String deliveryMethodName;
    public String deliveryTypeCode;
    public String address;
    public String recipient;
    public String phone;
    public java.util.ArrayList<TDeliveryMethodExtension> deliveryMethodExtensions;
    public double maxWeight;
}
