package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TReArrangeDeliveryResult extends BaseModule<TReArrangeDeliveryResult> implements Serializable {
    public String message;
    public boolean status;
}
