package com.daigou.sg.rpc.checkout;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TReArrangeDeliveryInfo extends BaseModule<TReArrangeDeliveryInfo> implements Serializable {
    public String deliveryMethod;
    public int deliveryMethodId;
    public String receipient;
    public String phone;
    public java.util.ArrayList<TDeliveryMethodExtension> deliveryMethodExtensions;
    public String parcelNumber;
    public String deliveryDate;
    public String deliveryTimeSlot;
}
