package com.daigou.sg.rpc.register;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TUpdateUserCouponStatus extends BaseModule<TUpdateUserCouponStatus> implements Serializable {
    public boolean status;
    public String message;
}
