package com.daigou.sg.rpc.register;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TUserScanQRStatus extends BaseModule<TUserScanQRStatus> implements Serializable {
    public int status;
    public String message;
    public double amount;
}
