package com.daigou.sg.rpc.partnershop;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSellerCategory extends BaseModule<TSellerCategory> implements Serializable {
    public int id;
    public String categoryName;
    public String altCategoryName;
}
