package com.daigou.sg.rpc.partnershop;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSellerWithBannerAndProducts extends BaseModule<TSellerWithBannerAndProducts> implements Serializable {
    public TSeller seller;
    public java.util.ArrayList<TSellerProduct> products;
    public String bannerPic;
}
