package com.daigou.sg.rpc.partnershop;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSellerProduct extends BaseModule<TSellerProduct> implements Serializable {
    public String productName;
    public String productUrl;
    public String priceWithSymbol;
    public String productImage;
}
