package com.daigou.sg.rpc.partnershop;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSellerCategoryNew extends BaseModule<TSellerCategoryNew> implements Serializable {
    public int sellerCategoryId;
    public String categoryName;
    public java.util.ArrayList<String> bannerPics;
}
