package com.daigou.sg.rpc.customeraddress;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TAddressDetail extends BaseModule<TAddressDetail> implements Serializable {
    public String buildingType;
    public String block;
    public String street;
    public String unitStart;
    public String unitEnd;
    public String buildingName;
    public int customerAddressId;
    public int customerId;
    public String zipCode;
    public String address;
    public String addressToName;
    public String addressToPhone;
    public String destCode;
    public String company;
    public String remark;
    public String shipToAddress1;
    public String shipToAddress2;
    public String shipToCity;
    public String shipToState;
    public String floor;
    public String instruction;
    public String preferedDeliveryTime;
    public String subdistrict;
    public String district;
    public boolean isMajor;
}
