package com.daigou.sg.rpc.customeraddress;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TAddress extends BaseModule<TAddress> implements Serializable {
    public String zipCode;
    public String address;
    public boolean isMajor;
    public String addressToName;
    public String addressToPhone;
    public String shipToAddress1;
    public String shipToAddress2;
    public String shipToCity;
    public String shipToState;
    public String destCode;
    public String subdistrict;
    public String district;
}
