package com.daigou.sg.rpc.customeraddress;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSGAddress extends BaseModule<TSGAddress> implements Serializable {
    public String zipCode;
    public String addressToName;
    public String addressToPhone;
    public String floor;
    public String block;
    public String street;
    public String unit;
    public String companyName;
    public String buildingName;
    public String preferedDeliveryTime;
    public String instruction;
    public String buildingType;
    public boolean isMajor;
}
