package com.daigou.sg.rpc.shipforme;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

<<<<<<< 426d8c35cacb2945a2e01575b9ca889913f8c645
public enum TShipType implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("1")
	AA(1),
	@SerializedName("2")
	BB(2);


=======
public enum TShipType {
	@SerializedName("1")
	AA(1),
	@SerializedName("2")
	BB(2);

<<<<<<< 392a8a2f3c6c24710bc28cc677435ecb721b9830
>>>>>>> modify generated source files
=======

>>>>>>> change generated source files
	int type;

    TShipType(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
<<<<<<< 426d8c35cacb2945a2e01575b9ca889913f8c645
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
=======
        return String.valueOf(type);
>>>>>>> modify generated source files
    }
}
