package com.daigou.sg.rpc.primeorder;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TOffset extends BaseModule<TOffset> implements Serializable {
    public int id;
    public String balanceType;
    public double localTotal;
    public String note;
    public String createDate;
}
