package com.daigou.sg.rpc.primeorder;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimeShipment extends BaseModule<TPrimeShipment> implements Serializable {
    public int shipmentId;
    public String localDeliveryMethod;
    public String stationName;
    public String periodName;
    public String localDeliveryDate;
    public String shipToAddress;
    public String shipToName;
    public String shipToPhone;
    public String shipToZip;
    public String shipToCity;
    public String shipToState;
    public String regionName;
    public String regionId;
    public String mrtStationItemId;
    public String neighbourhoodStationItemId;
    public int selfStationId;
    public double total;
    public String dayOfWeek;
    public boolean isEzShipping;
    public boolean canBeEdited;
    public String paymentNumber;
    public String status;
    public java.util.ArrayList<TPrimeOrderDetail> tOrder;
    public java.util.ArrayList<String> packageNumbers;
    public java.util.ArrayList<TTitleValueItem> shipmentDetailItems;
    public String eta;
    public String statusDisplayText;
    public java.util.ArrayList<Integer> packageIds;
}
