package com.daigou.sg.rpc.primeorder;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimePaymentBillCategory extends BaseModule<TPrimePaymentBillCategory> implements Serializable {
    public String billCategoryCode;
    public String billCategoryName;
    public String altBillCategoryName;
    public String total;
}
