package com.daigou.sg.rpc.primeorder;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimeOrder extends BaseModule<TPrimeOrder> implements Serializable {
    public TPrimePaymentBill paymentBill;
    public java.util.ArrayList<TPrimeShipment> shipments;
}
