package com.daigou.sg.rpc.primeorder;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimeOrderDetail extends BaseModule<TPrimeOrderDetail> implements Serializable {
    public int id;
    public String orderNumber;
    public String productImage;
    public String productName;
    public boolean gstFee;
    public boolean insured;
    public int qty;
    public String sellerDiscount;
    public int packageId;
    public String unitPrice;
    public String sku;
    public String remark;
    public String productUrl;
    public java.util.ArrayList<TPrimeOrderRemark> orderRemarks;
    public boolean isRejected;
    public java.util.ArrayList<TOffset> offsets;
    public String originCode;
}
