package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCommission extends BaseModule<TCommission> implements Serializable {
    public double pickUp;
    public double web;
    public double app;
    public double firstPercent;
    public double unFirstPercent;
    public double placeOrder;
}
