package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TDeliveryMethod extends BaseModule<TDeliveryMethod> implements Serializable {
    public String deliveryCode;
    public String deliveryName;
    public java.util.ArrayList<TCollectionStation> collectionStations;
}
