package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TDeliveryJob extends BaseModule<TDeliveryJob> implements Serializable {
    public String ID;
    public int priority;
    public int customerId;
    public String customerName;
    public String address;
    public String postCode;
    public String telephone;
    public int deliveryDate;
    public String catalogCode;
    public java.util.ArrayList<TShipment> shipments;
    public String driverName;
    public int driverNo;
    public String smsStatus;
    public String status;
    public String source;
    public int rating;
    public boolean isLocked;
    public double latitude;
    public double longitude;
    public String nickname;
    public String signatureImage;
    public String remark;
    public String smsContent;
    public String eta;
    public String shift;
    public int signTime;
}
