package com.daigou.selfstation.rpc.selfstation;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TFuzzySearchType implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("2")
	EMAIL(2),
	@SerializedName("3")
	PARCELNUMBER(3),
	@SerializedName("0")
	NICKNAME(0),
	@SerializedName("1")
	PHONE(1);


	int type;

    TFuzzySearchType(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
