package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TMyJoinReply extends BaseModule<TMyJoinReply> implements Serializable {
    public TDelivery delivery;
    public java.util.ArrayList<TRegist> regist;
    public java.util.ArrayList<TSales> sales;
    public double totalPrice;
    public TPlaceOrder order;
}
