package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TParcel extends BaseModule<TParcel> implements Serializable {
    public String userName;
    public String phone;
    public String parcelNumber;
    public String status;
    public java.util.ArrayList<TParcelSection> sections;
    public int customerId;
}
