package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPDTSmsMessage extends BaseModule<TPDTSmsMessage> implements Serializable {
    public int customerId;
    public String phoneNumber;
    public String deliveryMethod;
    public String stationName;
}
