package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TRegist extends BaseModule<TRegist> implements Serializable {
    public int num;
    public double registUnitPrice;
    public double totalPrice;
    public int registType;
}
