package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSaveSubPkgInfo extends BaseModule<TSaveSubPkgInfo> implements Serializable {
    public String subPkgNum;
    public String BP;
    public int pkgId;
    public int shipmentId;
}
