package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSelfStationNamesReply extends BaseModule<TSelfStationNamesReply> implements Serializable {
    public int code;
    public String errMsg;
    public java.util.ArrayList<String> data;
}
