package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TShipment extends BaseModule<TShipment> implements Serializable {
    public int shipmentId;
    public String parcelNo;
    public String memo;
    public double weight;
    public String remark;
}
