package com.daigou.selfstation.rpc.selfstation;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSubPackage extends BaseModule<TSubPackage> implements Serializable {
    public String nickName;
    public String parcelNum;
    public String shelfNum;
    public double Weight;
    public int packageCount;
    public int boxCount;
    public java.util.ArrayList<String> boxNums;
    public boolean isLocked;
    public int customerId;
    public int shipmentId;
    public int packageId;
    public int deliveryHouse;
    public String packageScanLabelColor;
    public boolean isModifyed;
    public boolean isHandCreated;
    public String remark;
    public String boxNum;
    public String shipToName;
    public String shipToPhone;
    public TParcelPaymentInfo paymentInfo;
    public TParcelStationInfo station;
}
