package com.daigou.sg.webapi.apphomepage;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.Response.Listener;
import com.android.volley.VolleyError;
import com.daigou.sg.rpc.BaseModule;
import com.daigou.sg.rpc.GsonUtils;
import com.daigou.sg.rpc.RpcRequest;
import com.daigou.sg.rpc.RpcResponse;
import com.daigou.sg.rpc.TRpc;
import com.google.gson.Gson;

import java.nio.charset.Charset;

public class AppHomePageService {
    private static final Gson gson = GsonUtils.getGsonInstance();
    private static int msgID = 1;

    private AppHomePageService() {
        // Constructor hidden because this is a singleton
    }

    private static String getMsgID() {
        msgID += 1;
        return Integer.toString(msgID);
    }

    public static RpcRequest GetHomePageShowArea(final Listener<java.util.ArrayList<THomePageArea>> listener) {
        RpcResponse res = new RpcResponse(THomePageArea.class, listener, true,false);
        java.util.HashMap<String, Object> args = null;

        RpcRequest req = new RpcRequest(Request.Method.POST, TRpc.getWebApiUrl() + "AppHomePage/GetHomePageShowArea", res, args);
        TRpc.getQueue().add(req);
        return req;
    }
}
