package com.daigou.sg.webapi.apphomepage;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TGroupLayoutInfo extends BaseModule<TGroupLayoutInfo> implements Serializable {
    public TLayoutType layoutType;
    public int columnCount;
    public double cellRatio;
}
