package com.daigou.sg.webapi.apphomepage;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class THomePageEntrance extends BaseModule<THomePageEntrance> implements Serializable {
    public String name;
    public String imageURL;
    public String link;
}
