package com.daigou.sg.webapi.apphomepage;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TLayoutType implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("1")
	ACTIVITY(1),
	@SerializedName("2")
	GRID(2),
	@SerializedName("3")
	BANNER(3),
	@SerializedName("4")
	LIST(4),
	@SerializedName("0")
	OTHER(0);


	int type;

    TLayoutType(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
