package com.daigou.sg.webapi.apphomepage;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TShowArea implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("2")
	SHOPPINGGUIDE(2),
	@SerializedName("3")
	HOT(3),
	@SerializedName("0")
	OTHER(0),
	@SerializedName("1")
	ACTIVITY(1);


	int type;

    TShowArea(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
