package com.daigou.sg.rpc.ezshipment;

import com.daigou.sg.rpc.BaseModule;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPackageDetail extends BaseModule<TPackageDetail> implements Serializable {
	@SerializedName("package")
    public TPackage tPackage;
    public java.util.ArrayList<com.daigou.sg.webapi.common.TOrderSimple> orders;
    public java.util.ArrayList<TParcelRemark> remarks;
    public boolean deliveryEditable;
    public java.util.ArrayList<com.daigou.sg.rpc.primeorder.TTitleValueItem> deliveryInfos;
    public java.util.ArrayList<com.daigou.sg.rpc.primeorder.TTitleValueItem> billInfos;
    public String imageUrl;
}
