package com.daigou.sg.rpc.ezshipment;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TPackageAction implements java.io.Serializable, com.daigou.sg.rpc.DeserializerEnum {
	@SerializedName("0")
	NONE(0),
	@SerializedName("1")
	ARRANGEDELIVERY(1),
	@SerializedName("2")
	ACKNOWLEDGE(2),
	@SerializedName("3")
	PAY(3);


	int type;

    TPackageAction(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return Integer.toString(type);
    }

    @Override
    public int getValue() {
        return type;
    }
}
