package com.daigou.sg.rpc.my.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TArrivedOrder extends BaseModule<TArrivedOrder> implements Serializable {
    public int id;
    public String orderNumber;
    public String productName;
    public String productImage;
    public String originCode;
    public String vendorName;
    public String warehouseCode;
    public String shipmentTypeId;
    public String altShipmentTypeName;
    public String orderDiscount;
    public double chargeWeight;
    public double orderWeight;
}
