package com.daigou.sg.rpc.my.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCredit extends BaseModule<TCredit> implements Serializable {
    public int credit;
    public int offset;
    public String imageUrl;
    public String title;
}
