package com.daigou.sg.rpc.my.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCreatedPaymentBillStatus extends BaseModule<TCreatedPaymentBillStatus> implements Serializable {
    public boolean status;
    public int shipmentId;
    public boolean isPayed;
    public String paymentNumber;
    public String submitMessage;
}
