package com.daigou.sg.rpc.my.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TMYCollectionMethod extends BaseModule<TMYCollectionMethod> implements Serializable {
    public String deliveryMethodCode;
    public String deliveryMethodName;
    public String desc;
    public double minFee;
    public double minWeight;
    public double maxFee;
    public double maxWeight;
    public double nightMaxWeight;
    public boolean hasSubMethods;
    public java.util.ArrayList<TSelfStation> stations;
}
