package com.daigou.sg.rpc.my.customer;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TSubmitParcel extends BaseModule<TSubmitParcel> implements Serializable {
    public java.util.ArrayList<Integer> orderIds;
    public String shipmentTypeCode;
    public String originCode;
    public String warehouseCode;
    public String localDeliveryMethod;
    public int customerAddressId;
    public int selfStationId;
    public String shipToName;
    public String shipToPhone;
    public String licenseNumber;
    public String periodName;
    public String coupon;
    public int credit;
    public boolean insurance;
}
