package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TAgentProduct extends BaseModule<TAgentProduct> implements Serializable {
    public long id;
    public String vendorName;
    public String productName;
    public String url;
    public double price;
    public int qty;
    public long cid;
    public double internalShipmentFee;
    public int shipmentTypeId;
    public String remark;
    public String productImage;
    public boolean insured;
    public String warehouseCode;
    public String originCode;
    public double weight;
    public double volumeWeight;
    public String skuProperties;
    public String sku;
    public String shopName;
    public String purchaseSource;
    public long skuId;
    public String skuImg;
    public String altShipmentTypeName;
    public String shipmentTypeCode;
    public boolean isEZBuy;
    public String category;
    public boolean isFlashProduct;
    public boolean isCashOffProduct;
}
