package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TBasketItem extends BaseModule<TBasketItem> implements Serializable {
    public int id;
    public TAgentProduct agentProduct;
    public boolean isFavorite;
    public double rebateDiscount;
    public double localShipmentFee;
    public double localUnitPrice;
    public double gstFee;
    public double handlingFee;
    public boolean selectStatus;
    public double specialHandlingFeePercent;
    public double subTotal;
    public String sellerDiscount;
    public boolean canSelected;
    public boolean isFlashSales;
}
