package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TBasketItemDetail extends BaseModule<TBasketItemDetail> implements Serializable {
    public int id;
    public TCartProduct product;
    public String warehouseCode;
    public int shipmentTypeId;
    public String shipmentTypeCode;
    public int qty;
    public String remark;
    public boolean insured;
    public String originCode;
    public String skuProperties;
    public String sku;
    public double unitPrice;
    public double internalShipmentFee;
    public String url;
    public int agentProductId;
}
