package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCartItemQuantity extends BaseModule<TCartItemQuantity> implements Serializable {
    public int basketItemID;
    public int quantity;
}
