package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCartProduct extends BaseModule<TCartProduct> implements Serializable {
    public long cid;
    public String vendorName;
    public String productName;
    public double unitPrice;
    public double shippingFee;
    public String productUrl;
    public String productImage;
    public String originCode;
    public String shopName;
    public String location;
    public boolean isShippingFee;
    public String specialHandlingFeeMessage;
    public double specialHandlingFeePercent;
    public java.util.ArrayList<String> propertyNames;
    public java.util.ArrayList<String> descriptionImages;
    public boolean isEZBuy;
}
