package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCartSummary extends BaseModule<TCartSummary> implements Serializable {
    public java.util.ArrayList<TBasketItemSummary> vendors;
    public double totalAmount;
    public double customerPrepay;
    public int totalItemCount;
    public int selectedItemCount;
    public String authorizeForBalance;
}
