package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCartItemDetail extends BaseModule<TCartItemDetail> implements Serializable {
    public com.daigou.sg.rpc.product.TProductExtension productExtension;
    public String SKUProperties;
    public String remark;
    public int quantity;
    public String warehouse;
}
