package com.daigou.sg.rpc.shoppingcart;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TEditCartItemAttribute extends BaseModule<TEditCartItemAttribute> implements Serializable {
    public int basketItemID;
    public int quantity;
    public String SKU;
    public String SKUProperties;
    public String remark;
}
