package com.daigou.sg.rpc.payment;

import com.google.gson.annotations.SerializedName;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public enum TPaymentType {
	@SerializedName("1")
	PRODUCT(1),
	@SerializedName("2")
	PARCEL(2),
	@SerializedName("3")
	OTHER(3);


	int type;

    TPaymentType(int type) {
        this.type = type;
    }

	@Override
    public String toString() {
        return String.valueOf(type);
    }
}
