package com.daigou.sg.rpc.productreview;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TReview extends BaseModule<TReview> implements Serializable {
    public String id;
    public String productUrl;
    public int userID;
    public int rating;
    public int helpfulCount;
    public String comment;
    public java.util.ArrayList<String> pictures;
    public String createDate;
    public String nickName;
    public String profilePic;
    public boolean hasSetHelpful;
    public String sku;
    public int orderId;
    public int packageId;
}
