package com.daigou.sg.webapi.flashsales;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TFlashSalesProduct extends BaseModule<TFlashSalesProduct> implements Serializable {
    public String productUrl;
    public double productPrice;
    public int productStock;
    public double productOriginPrice;
    public String productImage;
    public String catalogCode;
    public String discount;
    public String productLocalPrice;
    public String productOriginLocalPrice;
    public String rebateProductUrl;
    public String productName;
    public int MainCategoryId;
}
