package com.daigou.sg.webapi.flashsales;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TFlashSalesSummary extends BaseModule<TFlashSalesSummary> implements Serializable {
    public java.util.ArrayList<TFlashSalesProduct> products;
    public long beginTimeSpan;
    public long endTimeSpan;
    public String settingId;
    public String salesName;
    public String mobileSalesName;
}
