package com.daigou.sg.webapi.flashsales;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TFlashSalesSetting extends BaseModule<TFlashSalesSetting> implements Serializable {
    public String settingId;
    public String salesName;
    public String salesStartTime;
    public String salesEndTime;
    public boolean isActive;
    public int limitation;
    public boolean usableCoupon;
}
