package com.daigou.sg.rpc.collection;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCollection extends BaseModule<TCollection> implements Serializable {
    public String id;
    public String name;
    public int productCount;
    public String pic1;
    public String pic2;
    public String pic3;
}
