package com.daigou.sg.rpc.collection;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TCollectionForList extends BaseModule<TCollectionForList> implements Serializable {
    public String id;
    public String name;
    public TProductSimple p1;
    public TProductSimple p2;
    public TProductSimple p3;
    public TProductSimple p4;
    public int productCount;
}
