package com.daigou.sg.rpc.collection;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TProductSimple extends BaseModule<TProductSimple> implements Serializable {
    public String url;
    public String name;
    public String price;
    public String picture;
    public int favouriteCount;
    public String originCode;
    public String vendorName;
    public String enName;
    public String customerLocalPrice;
    public boolean isEzBuy;
    public String originalLocalUnitPrice;
    public String discountRate;
    public boolean isCashOffProduct;
}
