package com.daigou.sg.rpc.payment;

import com.daigou.sg.rpc.BaseModule;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;

/**
 * This file is auto-generated by tgen
 * Don't change manually
 */

public class TPrimePaymentSetting extends BaseModule<TPrimePaymentSetting> implements Serializable {
    public String primeTypeName;
    public String price;
    public double priceAmount;
    public String originalPrice;
    public double originalPriceAmount;
    public boolean hasDiscount;
}
